on: 
    workflow_dispatch:

name: Deploy via FTP to Pharmacy Council UAT
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        
    - name: Install Dependencies
      run: |
        rm -f composer.lock
        composer install --no-dev --optimize-autoloader

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.pcghana.org
        username: ${{ secrets.ftp_username_pc_uat }}
        password: ${{ secrets.ftp_password_pc_uat }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.vscode/**
          **/build/**
          **/tests/**
          **/writable/**
          **.zip
