name: Post-deployment Check for Pharmacy Council UAT
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy via FTP to Pharmacy Council UAT"]
    types:
      - completed

jobs:
  call-migration-url:
    runs-on: ubuntu-latest
    
    steps:
      - name: Call URL
        run: |
          response=$(curl -s https://testmanagement.pcghana.org/api/migrate)
          echo "Response from URL:"
          echo "$response"