name: Post-deployment Check
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy via FTP"]
    types:
      - completed

jobs:
  call-migration-url:
    runs-on: ubuntu-latest
    
    steps:
      - name: Call URL
        run: |
          response=$(curl -s https://licensing.druglanepms.com/api/migrate)
          echo "Response from URL:"
          echo "$response"